version: '3.8'

services:
  django-backend: 
    container_name: backend4${COMPOSE_PROJECT_NAME} 
    #image: juanpduque/digital-twin-platform-backend:test 
    build: .
    ports:
      #- 8000:8000
      - 80:80
    env_file:
      - .env  

  postgres-db:
    image: postgis/postgis:13-3.3-alpine
    volumes:
      - postgis-data:/var/lib/postgresql
    env_file:
      - .env
    ports:
      - 5432:5432
    restart: on-failure

volumes:
  postgis-data:
    name: ${COMPOSE_PROJECT_NAME}-postgis