# Generated by Django 4.2 on 2023-04-21 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('scenario_json', models.JSONField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scenario',
                'verbose_name_plural': 'Scenarios',
                'db_table': 'scenario',
            },
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField(null=True)),
                ('layer_name', models.CharField(max_length=256, null=True)),
                ('readable_name', models.CharField(default='', max_length=256)),
                ('description', models.TextField(default='')),
                ('keywords', models.TextField(blank=True, default='', null=True)),
                ('type', models.CharField(choices=[('WFS', 'WFS'), ('WMS', 'WMS'), ('WMST', 'WMST'), ('ARCGIS_IS', 'ArcGIS ImageServer'), ('ARCGIS_MS', 'ArcGIS MapServer')], max_length=256)),
                ('parameters', models.TextField(blank=True, default='')),
                ('frequency', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('units', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('service_url', models.TextField(null=True)),
                ('metadata_url', models.TextField(null=True)),
                ('legend_url', models.TextField(null=True)),
                ('more_data_url', models.TextField(null=True)),
                ('copyright', models.TextField(null=True)),
                ('initial_time_range', models.DateField(blank=True, null=True)),
                ('final_time_range', models.DateField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='layers', to='api.category')),
            ],
            options={
                'verbose_name': 'Layer',
                'verbose_name_plural': 'Layers',
                'db_table': 'layer',
            },
        ),
    ]
