# Generated by Django 4.2 on 2023-05-19 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='layer',
            old_name='description',
            new_name='abstract',
        ),
        migrations.RenameField(
            model_name='layer',
            old_name='readable_name',
            new_name='verbose_name',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='copyright',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='legend_url',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='metadata_url',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='more_data_url',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='service_url',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='type',
        ),
        migrations.CreateModel(
            name='LayerService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('WFS', 'WFS'), ('WMS', 'WMS'), ('WMST', 'WMST'), ('WCS', 'WCS'), ('ARCGIS_IS', 'ArcGIS ImageServer'), ('ARCGIS_MS', 'ArcGIS MapServer')], max_length=256)),
                ('url', models.TextField(null=True)),
                ('wrapper_name', models.CharField(max_length=256)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.layer')),
            ],
        ),
    ]
