# Generated by Django 4.2 on 2023-09-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_description_layer_abstract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='legend_url',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='layer',
            name='metadata_url',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='layer',
            name='service_url',
            field=models.CharField(default='', max_length=512),
        ),
    ]
