# Generated by Django 4.2 on 2023-09-13 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_layer_legend_url_layer_metadata_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layer',
            name='legend_url',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='metadata_url',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='service_url',
        ),
    ]
